<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FirstChkBox</name>
   <tag></tag>
   <elementGuidId>e670ce75-582e-4aa1-802f-1f8ef9b54b15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/mat-checkbox/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/mat-checkbox/label/div</value>
   </webElementProperties>
</WebElementEntity>
