<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Scripts_Run</name>
   <tag></tag>
   <elementGuidId>d51fd014-1cd9-4565-bcf5-4ea416ec3877</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-tab-content-4-0&quot;]/div/mat-card-content/div/div[1]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-tab-content-4-0&quot;]/div/mat-card-content/div/div[1]/button/span</value>
   </webElementProperties>
</WebElementEntity>
