<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AVG_No_Hrs_5</name>
   <tag></tag>
   <elementGuidId>594cad10-0d78-4f2b-aade-06649a4cb12e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-dashboard-card[@id='4']/mat-card/mat-card-header/div/mat-card-subtitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-card-subtitle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-card-subtitle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Last Updated: Nov 24, 2018 </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-container&quot;)/app-dashboard-card[@id=&quot;4&quot;]/mat-card[@class=&quot;card mat-card green&quot;]/mat-card-header[@class=&quot;mat-card-header&quot;]/div[@class=&quot;mat-card-header-text&quot;]/mat-card-subtitle[@class=&quot;mat-card-subtitle&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//app-dashboard-card[@id='4']/mat-card/mat-card-header/div/mat-card-subtitle</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On-site Time Spent0 - 2 Hrs'])[1]/following::mat-card-subtitle[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NA'])[2]/following::mat-card-subtitle[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On-site Time Spent2 - 4 Hrs'])[1]/preceding::mat-card-subtitle[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Updated: Nov 24, 2018'])[4]/preceding::mat-card-subtitle[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//app-dashboard-card[5]/mat-card/mat-card-header/div/mat-card-subtitle</value>
   </webElementXpaths>
</WebElementEntity>
