<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MagnificationGlass</name>
   <tag></tag>
   <elementGuidId>59868319-73da-4dbd-bb7c-ad06b6cfda4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-expansion-panel-header-0&quot;]/span/mat-panel-title/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-expansion-panel-header-0&quot;]/span/mat-panel-title/img</value>
   </webElementProperties>
</WebElementEntity>
